version: 2.1

orbs:
  ruby: circleci/ruby@1.1.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: pg
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: test

    working_directory: ~/project

    steps:
      - checkout:
          path: ~/project/rails_template

      - run:
          name: Install rails 6
          command: |
            gem install bundler -v 2.1.4
            gem install rails -v "~> 6"
            rails -v

      - run:
          name: Set git user
          command: |
            # This is just to not fail when the template creates the first commit
            git config --global user.email "test@example.com"
            git config --global user.name "Test user"

      - run:
          name: Generate rails app using template
          command: |
            rails new blog -d postgresql \
              --skip-sprockets --skip-turbolinks --skip-test --api --skip-bundle \
              -m ~/project/rails_template/template.rb
      - run:
          name: Create .env file
          command: |
            cd blog
            echo "APP_DB_HOST=localhost" >> .env
            echo "APP_DB_PORT=5432" >> .env
            echo "APP_DB_USER=pg" >> .env
            echo "APP_DB_PASSWORD=''" >> .env

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run bin/setup script
          command: |
            cd blog
            bin/setup

