version: 2.1

orbs:
  ruby: circleci/ruby@1.1.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: demo-ruby
          POSTGRES_DB: rails_blog_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/project

    steps:
      - checkout:
          path: ~/project/rails_template

      - run:
          name: Install rails 6
          command: |
            gem install bundler -v 2.1.4
            gem install rails -v "~> 6"
            rails -v

      - run:
          name: Set git user
          command: |
            git config --global user.email "test@example.com"
            git config --global user.name "Test user"

      - run:
          name: Generate rails app using template
          command: rails new blog -d postgresql -m ~/project/rails_template/template.rb