version: 2.1

references:
  workspace_path: &workspace_path /home/circleci/project
  rails_template_dir: &rails_template_dir /home/circleci/project/rails_template
  blog_dir: &blog_dir /home/circleci/project/blog

orbs:
  ruby: circleci/ruby@1.1.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: pg
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: test

    environment:
      BLOG_DIR: *blog_dir
      RAILS_TEMPLATE_DIR: *rails_template_dir

    working_directory: *workspace_path

    steps:
      - checkout:
          path: *rails_template_dir

      - run:
          name: Install rails 6
          command: |
            gem install bundler -v 2.1.4
            gem install rails -v "~> 6"
            rails -v

      - run:
          name: Set git user
          command: |
            # This is just to not fail when the template creates the first commit
            git config --global user.email "test@example.com"
            git config --global user.name "Test user"

      - run:
          name: Generate rails app using template
          command: |
            rails new blog -d postgresql \
              --skip-sprockets --skip-turbolinks --skip-test --api --skip-bundle \
              -m $RAILS_TEMPLATE_DIR/template.rb
      - run:
          name: Create .env file
          command: |
            cd $BLOG_DIR
            echo "APP_DB_HOST=localhost" >> .env
            echo "APP_DB_PORT=5432" >> .env
            echo "APP_DB_USER=pg" >> .env
            echo "APP_DB_PASSWORD=''" >> .env

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run bin/setup script
          command: cd $BLOG_DIR && bin/setup

      - run:
          name: Prepare for test
          command: |
            cd $BLOG_DIR

            rails g scaffold Post title:string content:text --no-routing-specs --no-request-specs
            rails db:migrate RAILS_ENV=test

            cp -rfv $RAILS_TEMPLATE_DIR/test/app $BLOG_DIR
            cp -rfv $RAILS_TEMPLATE_DIR/test/spec $BLOG_DIR

      - run:
          name: Run tests
          command: |
            cd $BLOG_DIR
            bundle exec rake factory_bot:lint RAILS_ENV=test
            COVERAGE=true bundle exec rspec
